service: serverless-ci-cd-test

provider:
  name: aws
  deploymentMethod: direct
  runtime: nodejs18.x
  memorySize: 128
  stage: ${opt:stage, 'development'}
  region: us-east-1

  environment: 
    SQS_QUEUE_URL: { Ref: TestQueue }
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - sqs:*
          Resource: 
            Fn::GetAtt: [ TestQueue, Arn ]

resources: 
  Resources: 
    TestQueue:
      Type: "AWS::SQS::Queue"
      Properties: 
        QueueName: ${self:provider.stage}-ci-cd-test-queue
        SqsManagedSseEnabled: false
custom:
  prune: 
    automatic: true
    number: 5
  deploymentStage: ${self:provider.stage}

functions: 
  manualTrigger: 
    handler: src/manualTrigger.handler
    events: 
      - http: 
          path: /manualTrigger
          method: post
    iamRoleStatements: 
    - Effect: Allow
      Action: 
        - sqs:SendMessage
      Resource: 
        Fn::GetAtt: [ TestQueue, Arn ]
  queueTrigger: 
    handler: src/queueTrigger.handler
    events: 
      - sqs: 
          arn: 
            Fn::GetAtt: [ TestQueue, Arn ]
    iamRoleStatements: 
    - Effect: Allow
      Action: 
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
      Resource: 
        Fn::GetAtt: [ TestQueue, Arn ]
plugins: 
  - serverless-iam-roles-per-function
  - serverless-plugin-typescript